name: Deploy to server

on:
  push:
    branches: ["main-with-server"]

  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "vps"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: ./dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./dist
      - name: Run remote command via SSH
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          private_key: ${{ secrets.KEY }}
          host_fingerprint: 3072 SHA256:LQiX5W8T/EmUzz6MPy3PvJkPzfdRHWBtcshcXwjuGtE root@ov-f5c33f (RSA)
          command: /var/www/yadm/app/current/cleanUpForNewDeploy.sh
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./dist/*"
          target: "/var/www/yadm/app/current"
